# Generated by Django 5.2.6 on 2025-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('industry', models.CharField(verbose_name='industry')),
                ('size', models.CharField(verbose_name='company_size')),
                ('website', models.URLField(verbose_name='company_website')),
                ('headquarter', models.CharField(verbose_name='company_headquarter')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
