# Generated by Django 5.2.6 on 2025-09-29 22:56

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(verbose_name='program_type')),
                ('program_range', models.CharField(verbose_name='program_range')),
                ('timeframe', models.CharField(verbose_name='program_timeframe')),
                ('description_and_goals', django_quill.fields.QuillField()),
                ('compliance_requirement', models.CharField(blank=True, null=True, verbose_name='compliance_requirements')),
                ('request_questions', models.CharField(blank=True, null=True, verbose_name='Requests_OR_Questions')),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='program',
            field=models.OneToOneField(default=32, on_delete=django.db.models.deletion.CASCADE, to='bug_bounty.program', verbose_name='company_program'),
            preserve_default=False,
        ),
    ]
