# Generated by Django 5.2.6 on 2025-09-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0002_program_company_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='target_asset',
            field=models.TextField(blank=True, null=True, verbose_name='Target Assets and URLs'),
        ),
        migrations.AddField(
            model_name='program',
            name='vulnerability_interest',
            field=models.CharField(blank=True, null=True, verbose_name='Vulnerability Types of Interest'),
        ),
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.CharField(verbose_name='Company headquarter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bug_bounty.program', verbose_name='Company Program'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(verbose_name='Company size'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(verbose_name='Company website'),
        ),
        migrations.AlterField(
            model_name='program',
            name='compliance_requirement',
            field=models.CharField(blank=True, null=True, verbose_name='Compliance requirements'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_range',
            field=models.CharField(verbose_name='Program range'),
        ),
        migrations.AlterField(
            model_name='program',
            name='request_questions',
            field=models.CharField(blank=True, null=True, verbose_name='Requests or questions'),
        ),
        migrations.AlterField(
            model_name='program',
            name='timeframe',
            field=models.CharField(verbose_name='Program timeframe'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(verbose_name='Program type'),
        ),
    ]
