# Generated by Django 5.2.6 on 2025-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0003_vulnerabilities_program_target_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='target_asset',
            field=models.TextField(verbose_name='Target Assets and URLs'),
        ),
        migrations.AlterField(
            model_name='program',
            name='vulnerability_interest',
            field=models.CharField(verbose_name='Vulnerability Types of Interest'),
        ),
    ]
