# Generated by Django 5.2.6 on 2025-09-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0004_alter_program_target_asset_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vulnerabilities',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='type',
            new_name='program_type',
        ),
    ]
