# Generated by Django 5.2.6 on 2025-09-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0005_delete_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('fintech', 'Financial Technology'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-commerce'), ('saas', 'Software as a Service'), ('gaming', 'Gaming'), ('education', 'Education'), ('government', 'Government'), ('cryptocurrency', 'Cryptocurrency'), ('social-media', 'Social Media'), ('iot', 'Internet of Things'), ('other', 'Other')], verbose_name='Industry'),
        ),
    ]
