# Generated by Django 5.2.6 on 2025-09-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0006_alter_company_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
