# Generated by Django 5.2.6 on 2025-10-01 23:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0007_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('', 'Select your industry'), ('fintech', 'Financial Technology'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-commerce'), ('saas', 'Software as a Service'), ('gaming', 'Gaming'), ('education', 'Education'), ('government', 'Government'), ('cryptocurrency', 'Cryptocurrency'), ('social-media', 'Social Media'), ('iot', 'Internet of Things'), ('other', 'Other')], verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='program',
            name='compliance_requirement',
            field=models.TextField(blank=True, null=True, verbose_name='Compliance requirements'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_range',
            field=models.CharField(max_length=100, verbose_name='Program range'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('', 'Select program type'), ('public', 'Public Program (Open to all researchers)'), ('private', 'Private Program (Invite-only)'), ('hybrid', 'Hybrid (Start private, go public later)')], max_length=150, verbose_name='Program type'),
        ),
        migrations.AlterField(
            model_name='program',
            name='request_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Requests or questions'),
        ),
        migrations.AlterField(
            model_name='program',
            name='timeframe',
            field=models.CharField(choices=[('', 'Select timeframe'), ('asap', 'ASAP (Within 2 weeks)'), ('1-month', 'Within 1 month'), ('2-3-months', '2-3 months'), ('6-month', '6+ months'), ('planning', 'Still planning')], max_length=100, verbose_name='Program timeframe'),
        ),
        migrations.AlterField(
            model_name='program',
            name='vulnerability_interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('xss', ' Cross-Site Scripting (XSS)'), ('sql-injection', 'SQL Injection'), ('authentication', 'Authentication Bypass'), ('authorization', 'Authorization Issues'), ('data-exposure', 'Data Exposure'), ('rce', 'Remote Code Execution')], max_length=150, verbose_name='Vulnerability Types of Interest'),
        ),
    ]
