# Generated by Django 5.2.6 on 2025-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0008_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('', 'Select company size'), ('startup', 'Startup (1-10 employees)'), ('small', 'Small (11-50 employees)'), ('medium', 'Medium (51-200 employees)'), ('large', 'Large (201-1000 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], verbose_name='Company size'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_range',
            field=models.CharField(choices=[('5k-15k', '$5,000 - $15,000/year'), ('15k-50k', '$15,000 - $50,000/year'), ('50k-100k', '$50,000 - $100,000/year'), ('100k', '$100,000+/year')], default='5k-15k', max_length=100, verbose_name='Program range'),
        ),
    ]
