# Generated by Django 5.2.6 on 2025-10-03 08:30

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0009_alter_company_company_name_alter_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description_and_goals',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description and Goal'),
        ),
    ]
