# Generated by Django 5.2.6 on 2025-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0010_alter_program_description_and_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='...', verbose_name='Slug URL'),
        ),
    ]
