# Generated by Django 5.2.6 on 2025-10-03 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0012_alter_company_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=150, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('severity_level', models.CharField(choices=[('', 'Select severity'), ('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], verbose_name='Severity Level')),
                ('vulnerability_type', models.CharField(choices=[('', 'Select vulnerability type'), ('rce', 'Remote Code Execution'), ('sqli', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('csrf', 'Cross-Site Request Forgery'), ('auth', 'Authentication Issues'), ('authz', 'Authorization Issues'), ('data-exposure', 'Data Exposure'), ('session', 'Session Management'), ('crypto', 'Cryptographic Issues'), ('business-logic', 'Business Logic Flaw'), ('other', 'Other')], verbose_name='Vulnerability Type')),
                ('vulnerability_title', models.CharField(max_length=150, verbose_name='Vulnerability Title')),
                ('affected_url', models.URLField(verbose_name='Affected URL/System')),
                ('description', models.TextField(verbose_name='Description')),
                ('steps_to_reproduce', models.TextField(verbose_name='Steps to reproduce')),
                ('business_impact', models.TextField(verbose_name='Business Impact')),
                ('recommended_mitigation', models.TextField(blank=True, null=True, verbose_name='Recommended Mitigation')),
                ('tools_and_method', models.CharField(blank=True, null=True, verbose_name='Tools and Methods used')),
                ('discovery_timeline', models.CharField(blank=True, null=True, verbose_name='Discovery Mitigation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bug_bounty.company', verbose_name='Company')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bug_bounty.program', verbose_name='Program')),
            ],
        ),
    ]
