# Generated by Django 5.2.6 on 2025-10-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0013_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='program',
        ),
    ]
