# Generated by Django 5.2.6 on 2025-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0014_remove_reports_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='reports',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
