# Generated by Django 5.2.6 on 2025-10-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0015_alter_reports_options_reports_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='fullname',
            new_name='author',
        ),
    ]
