# Generated by Django 5.2.6 on 2025-10-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0016_rename_fullname_reports_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='bug_bounty.program', verbose_name='Company Program'),
        ),
    ]
